Update check-minimum-requirements.sh
getsentry/onpremise pull request #1061
Opened 2021-08-16 06:53 UTC by alex1702

Updatet minimum docker-compose version to 1.29.2.

I saw the new version 21.8 and just tried to update on my server. Unfortunately the **install.sh** script broke without a proper error message. Then I saw that the docker-compose version must be higher on the release, updated it on my server and the installer then ran through.
So that a proper error message should come here is my patch for the 21.8.0 .

2021-08-16 23:13 UTC, chadwhitacre commented
> Unfortunately the `install.sh` script broke without a proper error message. 

My hunch is that the script broke due to #1062. Can you review that ticket and confirm, @alex1702?

If so, then I don't believe that requiring an even _newer_ version of `docker-compose` is the right solution.

2021-08-16 23:15 UTC, chadwhitacre requested changes
Not sure we want to _increase_ `MIN_COMPOSE_VERSION` in light of #1062.

2021-08-17 12:48 UTC, BYK commented
@chadwhitacre I think there's a point here: we must have a test case with the minimum supported version of `docker-compose`. We may decide to have a matrix or just sticking with the oldest we support.

2021-08-17 14:25 UTC, chadwhitacre commented
@BYK So close this in favor of #1066, yes?

2021-08-17 14:39 UTC, BYK commented
>@BYK So close this in favor of #1066, yes?

Yup, let's do that. Thanks a lot @alex1702 for putting this up!

2021-08-17 14:39 UTC, closed without merging