Allow to limit clickhouse memory usage
getsentry/onpremise pull request #651
Opened 2020-08-29 09:07 UTC by renchap

Currently Clickhouse memory is not limited, and it requires at least 10G of memory by default.

In this PR, I introduce a way to configure Clickhouse max memory using an environment variable. I chose to set it relative to the host max memory rather than a fixed amount so it will adapt to the size of the host. This is especially useful for people deploying Sentry on hosts with limited memory.

See related discussion in #616

2020-08-31 11:16 UTC, BYK requested changes
Hi @renchap, thanks for taking the time to build this up! The Clickhouse repo recommends using a volume mount for this, which I also prefer: https://github.com/ClickHouse/ClickHouse/tree/v20.3.9.70-lts/docker/server#start-server-instance-with-custom-configuration

Would you mind making this so we just mount the config file to `/etc/clickhouse-server/config.xml`?

We do something very similar with `nginx` so I think you can just reuse that logic.

2020-08-31 11:17 UTC, BYK commented
@JTCunning adding you as the SME as I have no idea if the 30% ratio would cause any issues. Based on your comments on #616, I think this is safe for smaller scales which the on-premise repo is intended for.

2020-09-08 16:44 UTC, renchap commented
Thanks for patching my PR, I have been very busy in the last week and did not had time to make the change!

2020-09-08 18:06 UTC, BYK commented
Closing as #662 was merged instead.

2020-09-08 18:06 UTC, closed without merging