fix(clickhouse): default logger level set to information
getsentry/onpremise pull request #733
Opened 2020-11-09 13:58 UTC by soullivaneuh

fixes #701

2020-11-09 14:31 UTC, BYK requested changes

2020-11-09 14:31 UTC, BYK commented on clickhouse/config.xml
> +    </logger>
```suggestion
<logger>
    <level from_env="CLICKHOUSE_LOGGER_LEVEL" />
	<console>1</console>
</logger>
```

2020-11-09 14:31 UTC, BYK commented on docker-compose.yml
> +      CLICKHOUSE_LOGGER_LEVEL: information
```suggestion
      CLICKHOUSE_LOGGER_LEVEL: 'information'
```

Let's see if adding quotes around this fixes the issue. If this doesn't fix it, let's just hard-code `information` into the XML file for now. I've Googled this error to no avail.

2020-11-10 10:42 UTC, soullivaneuh commented
@BYK Changed applied and squashed.

2020-11-10 11:23 UTC, soullivaneuh commented
Tests are still failing, but I can't identify the real issue on the log. Did you catch it?

2020-11-10 18:25 UTC, BYK commented
```
clickhouse_1                   | Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Invalid argument: Not a valid log level, Stack trace (when copying this message, always include the lines below):
```

This is more informative. Maybe although they document the value as `information`, they actually use `info`? Wanna give that a try? (sorry this turned out to be uglier than it should be)

2020-11-10 18:26 UTC, BYK commented on docker-compose.yml
> +      CLICKHOUSE_LOGGER_LEVEL: 'information'
Let's try `info`?

```suggestion
      CLICKHOUSE_LOGGER_LEVEL: 'info'
```

2020-11-11 07:31 UTC, BYK reviewed
Let's just try hard-coding.

2020-11-11 07:31 UTC, BYK commented on clickhouse/config.xml
> +        <level from_env="CLICKHOUSE_LOGGER_LEVEL" />
```suggestion
        <level>information</level>
```

2020-11-11 07:31 UTC, BYK commented on docker-compose.yml
> +      CLICKHOUSE_LOGGER_LEVEL: 'info'
```suggestion
```

2020-11-11 13:14 UTC, BYK approved these changes
I guess Clickhouse has a bug for this one. I'll look and see if I can submit a patch upstream but until then, let's go with this hard-coded solution.

2020-11-11 13:14 UTC, merged