docs(): Add notice about breaking change for custom plugins
getsentry/onpremise pull request #985
Opened 2021-06-07 17:43 UTC by billyvg

This adds a breaking change notice to our changelog regarding custom plugins:

The frontend bundle will be loaded asynchronously. This is a breaking change that can affect custom plugins that access certain globals in the django template. Please see https://forum.sentry.io/t/breaking-frontend-changes-for-custom-plugins/14184 for more information

2021-06-07 17:52 UTC, BYK requested changes

2021-06-07 17:52 UTC, BYK commented on CHANGELOG.md
> +- The frontend bundle will be loaded asynchronously. This is a breaking change that can affect custom plugins that access certain globals in the django template. Please see https://forum.sentry.io/t/
Let's align this with the commit log format we are already following<sup>[1](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format),[2](https://github.com/semantic-release/semantic-release)</sup>:

```suggestion
- BREAKING CHANGE: The frontend bundle will be loaded asynchronously. This is a breaking change that can affect custom plugins that access certain globals in the django template. Please see https://forum.sentry.io/t/breaking-frontend-changes-for-custom-plugins/14184 for more information.
```

2021-06-23 18:52 UTC, BYK approved these changes

2021-06-23 18:53 UTC, billyvg commented
@BYK Give me a bit to add a link to the PR

2021-06-29 10:44 UTC, merged